### PR TITLE
Updated positionSinonym array keys. Position settings bug fixed.

### PR DESCRIPTION
**Pull request by sinanselvi**

### CODE REVIEW

**Comment by bvamos** [comment]
Hi, would you merge this?

**Review by sinanselvi — COMMENTED** [review]
review

**Comment by odahcam** [comment]
The `positionSinonym` are right, why would I change that? 🤔

**Comment by sinanselvi** [comment]
> The `positionSinonym` are right, why would I change that? 🤔

Old version did not work for my project. Updated version work for me. If your code is correct, you can cancel it.  A lot of time has passed. I dont remember what i did 😄

**Comment by bvamos** [comment]
In fact, only synonyms worked for, based on the documentation.

**Comment by odahcam** [comment]
There's probably some error in another section of the code 😄 , but the object should be that way indeed. Thanks for the PR BTW.

**Pull request closed without merging**
